#!/usr/bin/env bash
set -e

echo Installing uqbarup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
UQBAR_DIR=${UQBAR_DIR-"$BASE_DIR/.uqbar"}
UQBAR_BIN_DIR="$UQBAR_DIR/bin"

REPO_URL="https://github.com/uqbar-dao/uqbarup.git"
UQBAR_REPO="$UQBAR_DIR/uqbarup"
UQBAR_SCRIPT="$UQBAR_BIN_DIR/uqbar"

# Create the .uqbar bin directory and uqbarup binary if it doesn't exist.

mkdir -p $UQBAR_BIN_DIR
rm -rf $UQBAR_REPO
cd $UQBAR_DIR
git clone $REPO_URL

# get uqbar script into proper location
cp "$UQBAR_REPO/uqbar/uqbar" "$UQBAR_BIN_DIR/uqbar"

# build relevant 
wasm-tools component wit "$UQBAR_REPO/wit/" -o "$UQBAR_REPO/target.wasm" --wasm
touch "$UQBAR_REPO/world"

chmod +x $UQBAR_SCRIPT

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "uqbarup: could not detect shell, manually add ${UQBAR_DIR} to your PATH."
    exit 1
esac

# Only add uqbarup if it isn't already in PATH.
if [[ ":$PATH:" != *":${UQBAR_SCRIPT}:"* ]]; then
    # Add the uqbarup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$UQBAR_SCRIPT\"" >> $PROFILE
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added uqbarup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use uqbarup."
