#!/usr/bin/env bash
set -e

echo Installing uqbarup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
UQBAR_DIR=${UQBAR_DIR-"$BASE_DIR/.uqbar"}
UQBAR_BIN_DIR="$UQBAR_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/uqbar-dao/uqbarup/main/upqbarup/install"
BIN_PATH="$UQBAR_BIN_DIR/uqbarup"


# Create the .uqbar bin directory and uqbarup binary if it doesn't exist.
mkdir -p $UQBAR_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "uqbarup: could not detect shell, manually add ${UQBAR_BIN_DIR} to your PATH."
    exit 1
esac

# Only add uqbarup if it isn't already in PATH.
if [[ ":$PATH:" != *":${UQBAR_BIN_DIR}:"* ]]; then
    # Add the uqbarup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$UQBAR_BIN_DIR\"" >> $PROFILE
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added uqbarup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use uqbarup."
echo "Then, simply run 'uqbarup' to install Foundry."
